services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: culinary_client
    environment:
      DISPLAY: ${DISPLAY}
      API_URL: "http://localhost:8080/api"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    stdin_open: true
    tty: true
